version: "2.2"
   
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=z1.settings
      - POSTGRES_NAME=entrevista
      - POSTGRES_USER=z1
      - POSTGRES_PASSWORD=adminZ1
    depends_on:
      - db